FROM node:22-alpine
# Instalar OpenSSL e dependências de compilação
RUN apk add --no-cache openssl build-base
# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app
# Copie apenas package.json e package-lock.json para o contêiner e instale as dependências
COPY package*.json ./
RUN npm install
# Copie o restante do código-fonte para o contêiner
COPY . .
# Declara os argumentos que serão usados como variáveis de ambiente
ARG PORT
# Configuração das variáveis de ambiente
ENV PORT=${PORT} 
    
# Expõe a porta que sua aplicação usará
EXPOSE ${PORT}
# Comando para executar a aplicação
CMD ["sh", "-c", "sleep 5 && npx prisma migrate deploy && npx prisma generate && npm run start:dev"]